#!/bin/bash

# generate_alertmanager_config.sh - Generate alertmanager.yml with environment variables
# This script is called by docker-compose to inject credentials from .env.local

set -euo pipefail

# Source environment variables
if [ -f .env.local ]; then
	set -a
	source .env.local
	set +a
fi

# Set defaults if not provided
SMTP_HOST="${SMTP_HOST:-smtp.gmail.com:587}"
ALERT_EMAIL_FROM="${ALERT_EMAIL_FROM:-alerts@example.com}"
SMTP_USER="${SMTP_USER-}"
SMTP_PASSWORD="${SMTP_PASSWORD-}"
CRITICAL_EMAIL_TO="${CRITICAL_EMAIL_TO:-ops@example.com}"

# Generate alertmanager.yml with actual values
cat >config/alertmanager.yml <<EOF
# Alertmanager Configuration for Loans Loans Analytics
# ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
# Generated by: scripts/monitoring/generate_alertmanager_config.sh
# Source: .env.local

global:
  resolve_timeout: 5m
  # SMTP configuration for email notifications
  smtp_smarthost: '${SMTP_HOST}'
  smtp_from: '${ALERT_EMAIL_FROM}'
  smtp_auth_username: '${SMTP_USER}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

# Templates for alert formatting
templates:
  - "/etc/alertmanager/templates/*.tmpl"

# Route tree
route:
  receiver: default-receiver
  group_by: ["alertname", "cluster", "service"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h

  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: critical-alerts
      group_wait: 0s
      repeat_interval: 5m

    # Warning alerts - batched notifications
    - match:
        severity: warning
      receiver: warning-alerts
      group_wait: 30s
      repeat_interval: 1h

    # Info alerts - daily summary
    - match:
        severity: info
      receiver: info-alerts
      repeat_interval: 24h

# Receivers (notification channels)
receivers:
  - name: default-receiver
    email_configs:
      - to: ${CRITICAL_EMAIL_TO}
        headers:
          Subject: '🔔 Alert: {{ .GroupLabels.alertname }}'
        html: |
          <h3>{{ .GroupLabels.alertname }}</h3>
          {{ range .Alerts }}
          <p><strong>Summary:</strong> {{ .Annotations.summary }}</p>
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
          {{ end }}
        send_resolved: true

  - name: critical-alerts
    email_configs:
      - to: ${CRITICAL_EMAIL_TO}
        headers:
          Subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        html: |
          <h2 style="color: red;">🚨 CRITICAL ALERT</h2>
          <h3>{{ .GroupLabels.alertname }}</h3>
          {{ range .Alerts }}
          <p><strong>Summary:</strong> {{ .Annotations.summary }}</p>
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Component:</strong> {{ .Labels.component }}</p>
          {{ if .Annotations.action }}
          <p><strong>Action Required:</strong> {{ .Annotations.action }}</p>
          {{ end }}
          {{ if .Annotations.runbook }}
          <p><strong>Runbook:</strong> <a href="{{ .Annotations.runbook }}">{{ .Annotations.runbook }}</a></p>
          {{ end }}
          {{ end }}
        send_resolved: true

  - name: warning-alerts
    email_configs:
      - to: ${CRITICAL_EMAIL_TO}
        headers:
          Subject: '⚠️ WARNING: {{ .GroupLabels.alertname }}'
        send_resolved: true

  - name: info-alerts
    email_configs:
      - to: ${CRITICAL_EMAIL_TO}
        headers:
          Subject: 'ℹ️ INFO: {{ .GroupLabels.alertname }}'
        send_resolved: true

# Inhibition rules (prevent alert spam)
inhibit_rules:
  # Inhibit warning if critical alert is firing
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: ['alertname', 'cluster', 'service']

  # Inhibit info if warning or critical is firing
  - source_match_re:
      severity: ^(warning|critical)$
    target_match:
      severity: info
    equal: ['alertname', 'cluster', 'service']
EOF

echo "✅ Generated config/alertmanager.yml with credentials from .env.local"
