[mypy]
python_version = 3.11
files = python, src
exclude = (?x)(
    \.venv
    | \.lint_venv
    | node_modules
    | build
    | dist
  )
ignore_missing_imports = True
namespace_packages = True
explicit_package_bases = True
# TODO: remove after incremental fixes
warn_unused_ignores = True
show_error_codes = True
pretty = True
# Ignore untyped imports from third-party libraries
disallow_untyped_calls = False
disallow_untyped_defs = False

[mypy-requests.*]
ignore_missing_imports = True
