#!/bin/bash
set -euo pipefail

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║           GitHub Secrets Configuration Helper                    ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""

REPO_URL="${1:-.}"

echo "📋 REQUIRED SECRETS TO CREATE IN GITHUB"
echo "═════════════════════════════════════════════════════════════════"
echo ""
echo "Repository: $REPO_URL"
echo ""
echo "Go to: Settings → Secrets and variables → Actions"
echo ""
echo "Create the following secrets:"
echo ""
echo "1️⃣  OPENAI_API_KEY"
echo "    Format: [OPENAI_KEY_PATTERN] (see docs)"
echo "    Source: https://platform.openai.com/api-keys"
echo ""
echo "2️⃣  ANTHROPIC_API_KEY"
echo "    Format: [ANTHROPIC_KEY_PATTERN] (see docs)"
echo "    Source: https://console.anthropic.com"
echo ""
echo "3️⃣  AZURE_CLIENT_SECRET"
echo "    Format: [AZURE_CLIENT_SECRET_PATTERN] (see docs)"
echo "    Source: https://portal.azure.com → Entra ID → App Registrations"
echo ""
echo "4️⃣  HUBSPOT_API_KEY"
echo "    Format: [HUBSPOT_API_KEY_PATTERN] (see docs)"
echo "    Source: https://app.hubspot.com/l/private-apps"
echo ""
echo "5️⃣  GEMINI_API_KEY_SIMPLE"
echo "    Format: API key"
echo "    Source: https://aistudio.google.com/app/apikey"
echo ""
echo "═════════════════════════════════════════════════════════════════"
echo ""
echo "✅ After creating all secrets:"
echo "   1. Rotate old keys in each service"
echo "   2. Delete exposed credentials from git history"
echo "   3. Force push to overwrite remote"
echo "   4. Run: bfg --replace-text /tmp/secrets.txt ."
echo ""
