apiVersion: v1
kind: Service
metadata:
  name: analytics-api
  namespace: abaco-analytics
  labels:
    app: analytics-api
spec:
  selector:
    app: analytics-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
