"""Strategic reporting utilities for executive analytics outputs."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def resolve_exports_dir(root_dir: Path) -> Path:
    """Resolve the preferred exports directory."""
    candidates = [
        root_dir / "exports",
        root_dir / "data" / "archives" / "_exports",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return candidates[0]


def load_dashboard_metrics(root_dir: Path) -> dict[str, Any]:
    """Load dashboard metrics JSON generated by KPI exports."""
    exports_dir = resolve_exports_dir(root_dir)
    dashboard_path = exports_dir / "complete_kpi_dashboard.json"
    if not dashboard_path.exists():
        raise FileNotFoundError(
            f"Dashboard export not found: {dashboard_path}. Run KPI export generation first."
        )
    with dashboard_path.open("r", encoding="utf-8") as dashboard_file:
        return json.load(dashboard_file)


def _to_float(value: Any) -> float | None:
    """Convert value to float safely."""
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _status_marker(value: bool) -> str:
    """Return a markdown marker for boolean status."""
    return "✅" if value else "❌"


def build_strategic_summary(metrics: dict[str, Any]) -> dict[str, Any]:
    """Build normalized strategic summary from KPI dashboard export."""
    extended = metrics.get("extended_kpis", {})
    strategic = extended.get("strategic_confirmations", {})
    unit_economics = extended.get("unit_economics", [])
    forecast = extended.get("revenue_forecast_6m", [])
    opportunities = extended.get("opportunity_prioritization", [])
    governance = extended.get("data_governance", {})

    latest_unit = unit_economics[-1] if unit_economics else {}
    total_forecast = sum(
        _to_float(item.get("forecast_revenue_usd")) or 0.0 for item in forecast
    )

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "confirmations": {
            "cac_confirmed": bool(strategic.get("cac_confirmed")),
            "ltv_confirmed": bool(strategic.get("ltv_confirmed")),
            "margin_confirmed": bool(strategic.get("margin_confirmed")),
            "revenue_forecast_confirmed": bool(strategic.get("revenue_forecast_confirmed")),
        },
        "metrics": {
            "cac_usd": _to_float(strategic.get("latest_cac_usd") or latest_unit.get("cac_usd")),
            "ltv_usd": _to_float(
                strategic.get("latest_ltv_usd") or latest_unit.get("ltv_realized_usd")
            ),
            "gross_margin_pct": _to_float(
                strategic.get("latest_gross_margin_pct") or latest_unit.get("gross_margin_pct")
            ),
            "next_month_revenue_forecast_usd": _to_float(
                strategic.get("next_month_revenue_forecast_usd")
            ),
            "forecast_6m_total_usd": total_forecast,
        },
        "governance": {
            "quality_score": _to_float(governance.get("quality_score")),
            "duplicate_rate": _to_float(governance.get("duplicate_rate")),
            "freshness_days": governance.get("freshness_days"),
            "status": governance.get("governance_status"),
        },
        "top_opportunities": opportunities[:5],
        "forecast_rows": forecast,
    }


def render_strategic_markdown(summary: dict[str, Any], links: dict[str, str]) -> str:
    """Render strategic summary markdown report."""
    confirmations = summary["confirmations"]
    metrics = summary["metrics"]
    governance = summary["governance"]

    lines = [
        "# Strategic Executive Report",
        "",
        f"Generated at (UTC): `{summary['generated_at']}`",
        "",
        "## Dashboard Links",
        f"- Streamlit (Local): {links['streamlit_local']}",
        f"- Grafana (Local): {links['grafana_local']}",
        f"- Streamlit (Deployed): {links['streamlit_prod']}",
        f"- Dashboard Documentation: {links['dashboard_docs']}",
        "",
        "## Requirement Confirmation",
        f"- CAC: {_status_marker(confirmations['cac_confirmed'])}",
        f"- LTV: {_status_marker(confirmations['ltv_confirmed'])}",
        f"- Margins: {_status_marker(confirmations['margin_confirmed'])}",
        (
            "- Revenue forecasting: "
            f"{_status_marker(confirmations['revenue_forecast_confirmed'])}"
        ),
        "",
        "## Strategic Metrics",
        f"- CAC (USD): `{metrics['cac_usd']}`",
        f"- LTV Realized (USD): `{metrics['ltv_usd']}`",
        f"- Gross Margin (%): `{metrics['gross_margin_pct']}`",
        (
            "- Revenue forecast next month (USD): "
            f"`{metrics['next_month_revenue_forecast_usd']}`"
        ),
        f"- Revenue forecast 6M total (USD): `{metrics['forecast_6m_total_usd']}`",
        "",
        "## Data Governance",
        f"- Quality score: `{governance['quality_score']}`",
        f"- Duplicate rate: `{governance['duplicate_rate']}`",
        f"- Freshness (days): `{governance['freshness_days']}`",
        f"- Status: `{governance['status']}`",
        "",
        "## Top Opportunities",
    ]

    opportunities = summary.get("top_opportunities", [])
    if not opportunities:
        lines.append("- No prioritized opportunities available.")
    else:
        for opportunity in opportunities:
            lines.append(
                "- "
                f"{opportunity.get('client_segment', 'N/A')}: "
                f"priority `{opportunity.get('priority_score')}` | "
                f"portfolio `{opportunity.get('Portfolio_Value')}` | "
                f"delinquency `{opportunity.get('Delinquency_Rate')}`"
            )

    return "\n".join(lines) + "\n"


def write_strategic_report(
    summary: dict[str, Any],
    links: dict[str, str],
    output_dir: Path,
) -> tuple[Path, Path]:
    """Write strategic report artifacts (JSON + Markdown) to disk."""
    output_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    json_path = output_dir / f"strategic_report_{timestamp}.json"
    md_path = output_dir / f"strategic_report_{timestamp}.md"
    latest_json_path = output_dir / "strategic_report_latest.json"
    latest_md_path = output_dir / "strategic_report_latest.md"

    payload = {
        "summary": summary,
        "dashboard_links": links,
    }

    with json_path.open("w", encoding="utf-8") as json_file:
        json.dump(payload, json_file, indent=2)
    with latest_json_path.open("w", encoding="utf-8") as latest_json_file:
        json.dump(payload, latest_json_file, indent=2)

    markdown = render_strategic_markdown(summary, links)
    md_path.write_text(markdown, encoding="utf-8")
    latest_md_path.write_text(markdown, encoding="utf-8")

    return latest_json_path, latest_md_path
