-- Add compatibility columns/triggers so both legacy kpi_key model and id/name model can coexist.
-- Also seeds the requested KPI definitions.
-- Idempotent: safe to run multiple times.

BEGIN;

CREATE SCHEMA IF NOT EXISTS monitoring;

ALTER TABLE IF EXISTS monitoring.kpi_definitions
  ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS kpi_definitions_id_key ON monitoring.kpi_definitions(id);
CREATE UNIQUE INDEX IF NOT EXISTS kpi_definitions_name_key ON monitoring.kpi_definitions(name);

ALTER TABLE monitoring.kpi_definitions
  ALTER COLUMN direction SET DEFAULT 'higher_is_better',
  ALTER COLUMN "window" SET DEFAULT 'current',
  ALTER COLUMN basis SET DEFAULT 'portfolio',
  ALTER COLUMN owner_agent SET DEFAULT 'monitoring',
  ALTER COLUMN source_tables SET DEFAULT ARRAY[]::TEXT[],
  ALTER COLUMN version SET DEFAULT 'v1';

CREATE OR REPLACE FUNCTION monitoring.sync_kpi_definitions_compat()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.kpi_key IS NULL AND NEW.name IS NOT NULL THEN
    NEW.kpi_key := NEW.name;
  ELSIF NEW.name IS NULL AND NEW.kpi_key IS NOT NULL THEN
    NEW.name := NEW.kpi_key;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_kpi_definitions_compat ON monitoring.kpi_definitions;
CREATE TRIGGER trg_sync_kpi_definitions_compat
BEFORE INSERT OR UPDATE ON monitoring.kpi_definitions
FOR EACH ROW
EXECUTE FUNCTION monitoring.sync_kpi_definitions_compat();

ALTER TABLE IF EXISTS monitoring.kpi_values
  ADD COLUMN IF NOT EXISTS kpi_id BIGINT,
  ADD COLUMN IF NOT EXISTS value NUMERIC,
  ADD COLUMN IF NOT EXISTS "timestamp" TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'kpi_values_kpi_id_fkey'
      AND connamespace = 'monitoring'::regnamespace
  ) THEN
    ALTER TABLE monitoring.kpi_values
      ADD CONSTRAINT kpi_values_kpi_id_fkey
      FOREIGN KEY (kpi_id) REFERENCES monitoring.kpi_definitions(id);
  END IF;
END $$;

ALTER TABLE monitoring.kpi_values
  ALTER COLUMN status SET DEFAULT 'green',
  ALTER COLUMN snapshot_id SET DEFAULT 'manual',
  ALTER COLUMN as_of_date SET DEFAULT CURRENT_DATE,
  ALTER COLUMN computed_at SET DEFAULT NOW(),
  ALTER COLUMN run_id SET DEFAULT 'manual',
  ALTER COLUMN inputs_hash SET DEFAULT 'manual';

CREATE OR REPLACE FUNCTION monitoring.sync_kpi_values_compat()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.kpi_key IS NULL AND NEW.kpi_id IS NOT NULL THEN
    SELECT kd.kpi_key INTO NEW.kpi_key
    FROM monitoring.kpi_definitions kd
    WHERE kd.id = NEW.kpi_id;
  END IF;

  IF NEW.value_num IS NULL AND NEW.value IS NOT NULL THEN
    NEW.value_num := NEW.value;
  ELSIF NEW.value IS NULL AND NEW.value_num IS NOT NULL THEN
    NEW.value := NEW.value_num;
  END IF;

  IF NEW.computed_at IS NULL AND NEW."timestamp" IS NOT NULL THEN
    NEW.computed_at := NEW."timestamp";
  ELSIF NEW."timestamp" IS NULL AND NEW.computed_at IS NOT NULL THEN
    NEW."timestamp" := NEW.computed_at;
  END IF;

  IF NEW.as_of_date IS NULL AND NEW."timestamp" IS NOT NULL THEN
    NEW.as_of_date := NEW."timestamp"::DATE;
  ELSIF NEW."timestamp" IS NULL AND NEW.as_of_date IS NOT NULL THEN
    NEW."timestamp" := NEW.as_of_date::TIMESTAMPTZ;
  END IF;

  IF NEW.status IS NULL THEN
    NEW.status := 'green';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_kpi_values_compat ON monitoring.kpi_values;
CREATE TRIGGER trg_sync_kpi_values_compat
BEFORE INSERT OR UPDATE ON monitoring.kpi_values
FOR EACH ROW
EXECUTE FUNCTION monitoring.sync_kpi_values_compat();

INSERT INTO monitoring.kpi_definitions (name, category, description, unit) VALUES
('par_30', 'Asset Quality', 'Portfolio % at risk 30+ days', 'percent'),
('par_90', 'Asset Quality', 'Portfolio % at risk 90+ days', 'percent'),
('npl_rate', 'Asset Quality', 'Non-performing loan rate', 'percent'),
('collection_rate_6m', 'Cash Flow', '6-month collection rate', 'percent'),
('recovery_rate', 'Cash Flow', 'Recovery rate on defaults', 'percent'),
('portfolio_rotation', 'Growth', 'Portfolio rotation rate', 'percent'),
('disbursement_volume', 'Growth', 'Total disbursement volume', 'units'),
('new_loans', 'Growth', 'New loans originated', 'count'),
('total_aum', 'Portfolio Performance', 'Total assets under management', 'currency'),
('average_loan_size', 'Portfolio Performance', 'Average loan size', 'currency'),
('loan_count', 'Portfolio Performance', 'Total number of loans', 'count'),
('portfolio_yield', 'Portfolio Performance', 'Portfolio yield', 'percent'),
('active_borrowers', 'Customer Metrics', 'Active borrowers', 'count'),
('repeat_borrower_rate', 'Customer Metrics', 'Repeat borrower rate', 'percent'),
('processing_time', 'Operational Metrics', 'Average processing time', 'days'),
('automation_rate', 'Operational Metrics', 'Automation rate', 'percent')
ON CONFLICT (name) DO NOTHING;

COMMIT;
