"""Strategic reporting utilities for executive analytics outputs."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd

from backend.python.config import settings
from backend.python.kpis.catalog_processor import KPICatalogProcessor


def resolve_exports_dir(root_dir: Path) -> Path:
    """Resolve the preferred exports directory."""
    candidates = [
        root_dir / "exports",
        root_dir / "data" / "archives" / "_exports",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return candidates[0]


def load_dashboard_metrics(root_dir: Path) -> dict[str, Any]:
    """Load dashboard metrics JSON generated by KPI exports."""
    exports_dir = resolve_exports_dir(root_dir)
    dashboard_path = exports_dir / "complete_kpi_dashboard.json"
    if not dashboard_path.exists():
        raise FileNotFoundError(
            f"Dashboard export not found: {dashboard_path}. Run KPI export generation first."
        )
    with dashboard_path.open("r", encoding="utf-8") as dashboard_file:
        return json.load(dashboard_file)


def _to_float(value: Any) -> float | None:
    """Convert value to float safely."""
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _status_marker(value: bool) -> str:
    """Return a markdown marker for boolean status."""
    return "✅" if value else "❌"


def build_strategic_summary(metrics: dict[str, Any]) -> dict[str, Any]:
    """Build normalized strategic summary from KPI dashboard export."""
    extended = metrics.get("extended_kpis", {})
    strategic = extended.get("strategic_confirmations", {})
    unit_economics = extended.get("unit_economics", [])
    forecast = extended.get("revenue_forecast_6m", [])
    opportunities = extended.get("opportunity_prioritization", [])
    governance = extended.get("data_governance", {})

    latest_unit = unit_economics[-1] if unit_economics else {}
    total_forecast = sum(_to_float(item.get("forecast_revenue_usd")) or 0.0 for item in forecast)

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "confirmations": {
            "cac_confirmed": bool(strategic.get("cac_confirmed")),
            "ltv_confirmed": bool(strategic.get("ltv_confirmed")),
            "margin_confirmed": bool(strategic.get("margin_confirmed")),
            "revenue_forecast_confirmed": bool(strategic.get("revenue_forecast_confirmed")),
        },
        "metrics": {
            "cac_usd": _to_float(strategic.get("latest_cac_usd") or latest_unit.get("cac_usd")),
            "ltv_usd": _to_float(
                strategic.get("latest_ltv_usd") or latest_unit.get("ltv_realized_usd")
            ),
            "gross_margin_pct": _to_float(
                strategic.get("latest_gross_margin_pct") or latest_unit.get("gross_margin_pct")
            ),
            "next_month_revenue_forecast_usd": _to_float(
                strategic.get("next_month_revenue_forecast_usd")
            ),
            "forecast_6m_total_usd": total_forecast,
        },
        "governance": {
            "quality_score": _to_float(governance.get("quality_score")),
            "duplicate_rate": _to_float(governance.get("duplicate_rate")),
            "freshness_days": governance.get("freshness_days"),
            "status": governance.get("governance_status"),
        },
        "top_opportunities": opportunities[:5],
        "forecast_rows": forecast,
    }


def render_strategic_markdown(summary: dict[str, Any], links: dict[str, str]) -> str:
    """Render strategic summary markdown report."""
    confirmations = summary["confirmations"]
    metrics = summary["metrics"]
    governance = summary["governance"]

    lines = [
        "# Strategic Executive Report",
        "",
        f"Generated at (UTC): `{summary['generated_at']}`",
        "",
        "## Dashboard Links",
        f"- Streamlit (Local): {links['streamlit_local']}",
        f"- Grafana (Local): {links['grafana_local']}",
        f"- Streamlit (Deployed): {links['streamlit_prod']}",
        f"- Dashboard Documentation: {links['dashboard_docs']}",
        "",
        "## Requirement Confirmation",
        f"- CAC: {_status_marker(confirmations['cac_confirmed'])}",
        f"- LTV: {_status_marker(confirmations['ltv_confirmed'])}",
        f"- Margins: {_status_marker(confirmations['margin_confirmed'])}",
        (
            "- Revenue forecasting: "
            f"{_status_marker(confirmations['revenue_forecast_confirmed'])}"
        ),
        "",
        "## Strategic Metrics",
        f"- CAC (USD): `{metrics['cac_usd']}`",
        f"- LTV Realized (USD): `{metrics['ltv_usd']}`",
        f"- Gross Margin (%): `{metrics['gross_margin_pct']}`",
        ("- Revenue forecast next month (USD): " f"`{metrics['next_month_revenue_forecast_usd']}`"),
        f"- Revenue forecast 6M total (USD): `{metrics['forecast_6m_total_usd']}`",
        "",
        "## Data Governance",
        f"- Quality score: `{governance['quality_score']}`",
        f"- Duplicate rate: `{governance['duplicate_rate']}`",
        f"- Freshness (days): `{governance['freshness_days']}`",
        f"- Status: `{governance['status']}`",
        "",
        "## Top Opportunities",
    ]

    opportunities = summary.get("top_opportunities", [])
    if not opportunities:
        lines.append("- No prioritized opportunities available.")
    else:
        for opportunity in opportunities:
            lines.append(
                "- "
                f"{opportunity.get('client_segment', 'N/A')}: "
                f"priority `{opportunity.get('priority_score')}` | "
                f"portfolio `{opportunity.get('Portfolio_Value')}` | "
                f"delinquency `{opportunity.get('Delinquency_Rate')}`"
            )

    return "\n".join(lines) + "\n"


def write_strategic_report(
    summary: dict[str, Any],
    links: dict[str, str],
    output_dir: Path,
) -> tuple[Path, Path]:
    """Write strategic report artifacts (JSON + Markdown) to disk."""
    output_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    json_path = output_dir / f"strategic_report_{timestamp}.json"
    md_path = output_dir / f"strategic_report_{timestamp}.md"
    latest_json_path = output_dir / "strategic_report_latest.json"
    latest_md_path = output_dir / "strategic_report_latest.md"

    payload = {
        "summary": summary,
        "dashboard_links": links,
    }

    with json_path.open("w", encoding="utf-8") as json_file:
        json.dump(payload, json_file, indent=2, default=str)
    with latest_json_path.open("w", encoding="utf-8") as latest_json_file:
        json.dump(payload, latest_json_file, indent=2, default=str)

    markdown = render_strategic_markdown(summary, links)
    md_path.write_text(markdown, encoding="utf-8")
    latest_md_path.write_text(markdown, encoding="utf-8")

    return latest_json_path, latest_md_path


def _read_optional_table(file_path: Path) -> pd.DataFrame:
    """Read CSV/Parquet table when present; return empty frame when missing."""
    if not file_path.exists():
        return pd.DataFrame()
    if file_path.suffix.lower() == ".parquet":
        return pd.read_parquet(file_path)
    return pd.read_csv(file_path)


def _normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Normalize raw dataset column names to snake_case aliases used by KPI processors."""
    if df.empty:
        return df

    normalized = df.copy()
    normalized.columns = (
        normalized.columns.astype(str)
        .str.normalize("NFKD")
        .str.encode("ascii", "ignore")
        .str.decode("ascii")
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace(r"[^a-z0-9_]", "", regex=True)
    )

    alias_map = {
        "true_payment_date": "payment_date",
        "true_total_payment": "total_payment",
        "true_rabates": "true_rebates",
        "date_of_application": "created_at",
    }
    for source_col, target_col in alias_map.items():
        if source_col in normalized.columns and target_col not in normalized.columns:
            normalized = normalized.rename(columns={source_col: target_col})

    return normalized


def _build_guardrails() -> dict[str, float]:
    """Return guardrail thresholds used by official dashboard exports."""
    return {
        "min_rotation_x": settings.financial.min_rotation,
        "max_default_rate_pct": settings.financial.max_default_rate * 100,
        "max_top1_concentration_pct": settings.financial.max_single_obligor_concentration * 100,
        "max_top10_concentration_pct": settings.financial.max_top_10_concentration * 100,
        "target_apr_min_pct": settings.financial.target_apr_min * 100,
        "target_apr_max_pct": settings.financial.target_apr_max * 100,
        "max_cost_of_debt_pct": settings.financial.max_cost_of_debt * 100,
        "min_dscr": settings.financial.min_dscr,
        "utilization_min_pct": settings.financial.utilization_min * 100,
        "utilization_max_pct": settings.financial.utilization_max * 100,
        "min_ce_6m_pct": settings.financial.min_ce_6m * 100,
    }


def _status(ok: bool) -> str:
    """Return normalized dashboard status value."""
    return "ok" if ok else "breach"


def _build_guardrail_status(extended_kpis: dict[str, Any]) -> dict[str, dict[str, float | str | None]]:
    """Evaluate current KPI values against configured thresholds."""
    rotation = extended_kpis.get("portfolio_rotation", {})
    concentration = extended_kpis.get("concentration", {})
    dpd_buckets = extended_kpis.get("dpd_buckets", {})

    rotation_value = _to_float(rotation.get("rotation_x"))
    top1_value = _to_float(
        concentration.get("top_1_debtor_pct", concentration.get("top_1_pct"))
    )
    top10_value = _to_float(
        concentration.get("top_10_debtor_pct", concentration.get("top_10_pct"))
    )
    par30_value = _to_float(dpd_buckets.get("dpd_30_plus_pct"))
    par90_value = _to_float(dpd_buckets.get("dpd_90_plus_pct", dpd_buckets.get("dpd_90_plus")))
    npl180_value = _to_float(dpd_buckets.get("dpd_180_plus_pct"))

    return {
        "rotation": {
            "value": rotation_value,
            "target": settings.financial.min_rotation,
            "status": _status((rotation_value or 0.0) >= settings.financial.min_rotation),
        },
        "top1_debtor": {
            "value": top1_value,
            "target": settings.financial.max_single_obligor_concentration * 100,
            "status": _status(
                (top1_value or 100.0)
                <= (settings.financial.max_single_obligor_concentration * 100)
            ),
        },
        "top10_debtor": {
            "value": top10_value,
            "target": settings.financial.max_top_10_concentration * 100,
            "status": _status(
                (top10_value or 100.0) <= (settings.financial.max_top_10_concentration * 100)
            ),
        },
        "par30": {
            "value": par30_value,
            "target": 5.0,
            "status": _status((par30_value or 100.0) <= 5.0),
        },
        "par90": {
            "value": par90_value,
            "target": 2.0,
            "status": _status((par90_value or 100.0) <= 2.0),
        },
        "npl_180": {
            "value": npl180_value,
            "target": settings.financial.max_default_rate * 100,
            "status": _status((npl180_value or 100.0) <= (settings.financial.max_default_rate * 100)),
        },
    }


def _build_sql_view_mirrors(extended_kpis: dict[str, Any]) -> dict[str, Any]:
    """Return dashboard mirrors aligned with SQL KPI view naming."""
    executive_strip = extended_kpis.get("executive_strip", {})
    return {
        "kpi_monthly_pricing": extended_kpis.get("monthly_pricing", {}),
        "kpi_monthly_risk": extended_kpis.get("dpd_buckets", {}),
        "kpi_customer_types": extended_kpis.get("nsm_customer_types", {}),
        "kpi_concentration": extended_kpis.get("concentration", {}),
        "kpi_weighted_apr": {"weighted_apr": extended_kpis.get("weighted_apr", 0.0)},
        "kpi_weighted_fee_rate": {
            "weighted_fee_rate": extended_kpis.get("weighted_fee_rate", 0.0)
        },
        "kpi_active_unique_customers": {
            "count": executive_strip.get("total_customers", 0)
        },
        "kpi_average_ticket": {
            "avg_ticket_usd": _to_float(executive_strip.get("total_outstanding_loan_value")),
            "total_loans": executive_strip.get("total_loans", 0),
        },
    }


def _build_dashboard_payload(data_root: Path, extended_kpis: dict[str, Any]) -> dict[str, Any]:
    """Assemble the official KPI dashboard export payload."""
    executive_strip = extended_kpis.get("executive_strip", {})
    nsm = extended_kpis.get("nsm_customer_types", {})
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source_data_dir": str(data_root),
        "data_sources": [
            "loan_data.csv",
            "real_payment.csv",
            "customer_data.csv",
            "payment_schedule.csv",
        ],
        "kpi_groups_count": len([key for key in extended_kpis if not key.startswith("_")]),
        "extended_kpis": extended_kpis,
        "nsm": {
            "metric": "recurrent_tpv_12m_usd",
            "value": nsm.get("recurrent_tpv_12m_usd"),
            "pct_of_total": nsm.get("recurrent_tpv_12m_pct"),
            "recurrent_clients": nsm.get("recurrent_clients_12m"),
            "recurrent_rate_pct": nsm.get("recurrent_rate_12m_pct"),
            "new_clients_3m": nsm.get("new_count"),
            "recurrent_3m": nsm.get("recurrent_count"),
            "reactivated_3m": nsm.get("reactivated_count"),
        },
        "guardrails": _build_guardrails(),
        "guardrail_status": _build_guardrail_status(extended_kpis),
        "sql_view_mirrors": _build_sql_view_mirrors(extended_kpis),
        "aum_snapshot": {
            "total_outstanding_usd": executive_strip.get("total_outstanding_loan_value"),
            "total_loans": executive_strip.get("total_loans"),
            "total_customers": executive_strip.get("total_customers"),
        },
    }


def generate_strategic_report(data_dir: str | Path, exports_dir: str | Path) -> dict[str, str]:
    """Generate complete KPI dashboard JSON and strategic report artifacts.

    Input files are resolved under ``data_dir`` using canonical names:
    ``loan_data.csv``, ``real_payment.csv``, ``customer_data.csv``,
    and optional ``payment_schedule.csv``.
    """
    data_root = Path(data_dir)
    exports_root = Path(exports_dir)
    exports_root.mkdir(parents=True, exist_ok=True)

    loans_df = _normalize_columns(_read_optional_table(data_root / "loan_data.csv"))
    payments_df = _normalize_columns(_read_optional_table(data_root / "real_payment.csv"))
    customer_source = data_root / "customer_data.csv"
    if not customer_source.exists():
        customer_source = data_root / "customer.csv"

    customers_df = _normalize_columns(_read_optional_table(customer_source))
    schedule_df = _normalize_columns(_read_optional_table(data_root / "payment_schedule.csv"))

    if loans_df.empty and payments_df.empty and customers_df.empty:
        raise ValueError(
            "CRITICAL: No input datasets found in data_dir. "
            "Expected at least one of loan_data.csv, real_payment.csv, customer_data.csv"
        )

    processor = KPICatalogProcessor(
        loans_df=loans_df,
        payments_df=payments_df,
        customers_df=customers_df,
        schedule_df=schedule_df,
    )
    extended_kpis = processor.get_all_kpis()

    dashboard_payload = _build_dashboard_payload(data_root, extended_kpis)
    dashboard_path = exports_root / "complete_kpi_dashboard.json"
    with dashboard_path.open("w", encoding="utf-8") as dashboard_file:
        json.dump(dashboard_payload, dashboard_file, indent=2, default=str)

    summary = build_strategic_summary(dashboard_payload)
    links = {
        "streamlit_local": "http://localhost:8501",
        "grafana_local": "http://localhost:3001/dashboards",
        "streamlit_prod": "https://abaco-analytics-dashboard.azurewebsites.net",
        "dashboard_docs": "docs/analytics/dashboards.md",
    }
    latest_json_path, latest_md_path = write_strategic_report(summary, links, exports_root)

    return {
        "dashboard_json": str(dashboard_path),
        "strategic_report_json": str(latest_json_path),
        "strategic_report_md": str(latest_md_path),
    }
