"""Strategic reporting utilities for executive analytics outputs."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd

from backend.python.kpis.catalog_processor import KPICatalogProcessor


def resolve_exports_dir(root_dir: Path) -> Path:
    """Resolve the preferred exports directory."""
    candidates = [
        root_dir / "exports",
        root_dir / "data" / "archives" / "_exports",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return candidates[0]


def load_dashboard_metrics(root_dir: Path) -> dict[str, Any]:
    """Load dashboard metrics JSON generated by KPI exports."""
    exports_dir = resolve_exports_dir(root_dir)
    dashboard_path = exports_dir / "complete_kpi_dashboard.json"
    if not dashboard_path.exists():
        raise FileNotFoundError(
            f"Dashboard export not found: {dashboard_path}. Run KPI export generation first."
        )
    with dashboard_path.open("r", encoding="utf-8") as dashboard_file:
        return json.load(dashboard_file)


def _to_float(value: Any) -> float | None:
    """Convert value to float safely."""
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _status_marker(value: bool) -> str:
    """Return a markdown marker for boolean status."""
    return "✅" if value else "❌"


def build_strategic_summary(metrics: dict[str, Any]) -> dict[str, Any]:
    """Build normalized strategic summary from KPI dashboard export."""
    extended = metrics.get("extended_kpis", {})
    strategic = extended.get("strategic_confirmations", {})
    unit_economics = extended.get("unit_economics", [])
    forecast = extended.get("revenue_forecast_6m", [])
    opportunities = extended.get("opportunity_prioritization", [])
    governance = extended.get("data_governance", {})

    latest_unit = unit_economics[-1] if unit_economics else {}
    total_forecast = sum(_to_float(item.get("forecast_revenue_usd")) or 0.0 for item in forecast)

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "confirmations": {
            "cac_confirmed": bool(strategic.get("cac_confirmed")),
            "ltv_confirmed": bool(strategic.get("ltv_confirmed")),
            "margin_confirmed": bool(strategic.get("margin_confirmed")),
            "revenue_forecast_confirmed": bool(strategic.get("revenue_forecast_confirmed")),
        },
        "metrics": {
            "cac_usd": _to_float(strategic.get("latest_cac_usd") or latest_unit.get("cac_usd")),
            "ltv_usd": _to_float(
                strategic.get("latest_ltv_usd") or latest_unit.get("ltv_realized_usd")
            ),
            "gross_margin_pct": _to_float(
                strategic.get("latest_gross_margin_pct") or latest_unit.get("gross_margin_pct")
            ),
            "next_month_revenue_forecast_usd": _to_float(
                strategic.get("next_month_revenue_forecast_usd")
            ),
            "forecast_6m_total_usd": total_forecast,
        },
        "governance": {
            "quality_score": _to_float(governance.get("quality_score")),
            "duplicate_rate": _to_float(governance.get("duplicate_rate")),
            "freshness_days": governance.get("freshness_days"),
            "status": governance.get("governance_status"),
        },
        "top_opportunities": opportunities[:5],
        "forecast_rows": forecast,
    }


def render_strategic_markdown(summary: dict[str, Any], links: dict[str, str]) -> str:
    """Render strategic summary markdown report."""
    confirmations = summary["confirmations"]
    metrics = summary["metrics"]
    governance = summary["governance"]

    lines = [
        "# Strategic Executive Report",
        "",
        f"Generated at (UTC): `{summary['generated_at']}`",
        "",
        "## Dashboard Links",
        f"- Streamlit (Local): {links['streamlit_local']}",
        f"- Grafana (Local): {links['grafana_local']}",
        f"- Streamlit (Deployed): {links['streamlit_prod']}",
        f"- Dashboard Documentation: {links['dashboard_docs']}",
        "",
        "## Requirement Confirmation",
        f"- CAC: {_status_marker(confirmations['cac_confirmed'])}",
        f"- LTV: {_status_marker(confirmations['ltv_confirmed'])}",
        f"- Margins: {_status_marker(confirmations['margin_confirmed'])}",
        (
            "- Revenue forecasting: "
            f"{_status_marker(confirmations['revenue_forecast_confirmed'])}"
        ),
        "",
        "## Strategic Metrics",
        f"- CAC (USD): `{metrics['cac_usd']}`",
        f"- LTV Realized (USD): `{metrics['ltv_usd']}`",
        f"- Gross Margin (%): `{metrics['gross_margin_pct']}`",
        ("- Revenue forecast next month (USD): " f"`{metrics['next_month_revenue_forecast_usd']}`"),
        f"- Revenue forecast 6M total (USD): `{metrics['forecast_6m_total_usd']}`",
        "",
        "## Data Governance",
        f"- Quality score: `{governance['quality_score']}`",
        f"- Duplicate rate: `{governance['duplicate_rate']}`",
        f"- Freshness (days): `{governance['freshness_days']}`",
        f"- Status: `{governance['status']}`",
        "",
        "## Top Opportunities",
    ]

    opportunities = summary.get("top_opportunities", [])
    if not opportunities:
        lines.append("- No prioritized opportunities available.")
    else:
        for opportunity in opportunities:
            lines.append(
                "- "
                f"{opportunity.get('client_segment', 'N/A')}: "
                f"priority `{opportunity.get('priority_score')}` | "
                f"portfolio `{opportunity.get('Portfolio_Value')}` | "
                f"delinquency `{opportunity.get('Delinquency_Rate')}`"
            )

    return "\n".join(lines) + "\n"


def write_strategic_report(
    summary: dict[str, Any],
    links: dict[str, str],
    output_dir: Path,
) -> tuple[Path, Path]:
    """Write strategic report artifacts (JSON + Markdown) to disk."""
    output_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    json_path = output_dir / f"strategic_report_{timestamp}.json"
    md_path = output_dir / f"strategic_report_{timestamp}.md"
    latest_json_path = output_dir / "strategic_report_latest.json"
    latest_md_path = output_dir / "strategic_report_latest.md"

    payload = {
        "summary": summary,
        "dashboard_links": links,
    }

    with json_path.open("w", encoding="utf-8") as json_file:
        json.dump(payload, json_file, indent=2, default=str)
    with latest_json_path.open("w", encoding="utf-8") as latest_json_file:
        json.dump(payload, latest_json_file, indent=2, default=str)

    markdown = render_strategic_markdown(summary, links)
    md_path.write_text(markdown, encoding="utf-8")
    latest_md_path.write_text(markdown, encoding="utf-8")

    return latest_json_path, latest_md_path


def _read_optional_table(file_path: Path) -> pd.DataFrame:
    """Read CSV/Parquet table when present; return empty frame when missing."""
    if not file_path.exists():
        return pd.DataFrame()
    if file_path.suffix.lower() == ".parquet":
        return pd.read_parquet(file_path)
    return pd.read_csv(file_path)


def _normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Normalize raw dataset column names to snake_case aliases used by KPI processors."""
    if df.empty:
        return df

    normalized = df.copy()
    normalized.columns = (
        normalized.columns.astype(str)
        .str.normalize("NFKD")
        .str.encode("ascii", "ignore")
        .str.decode("ascii")
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace(r"[^a-z0-9_]", "", regex=True)
    )

    alias_map = {
        "true_payment_date": "payment_date",
        "true_total_payment": "total_payment",
        "true_rabates": "true_rebates",
        "date_of_application": "created_at",
    }
    for source_col, target_col in alias_map.items():
        if source_col in normalized.columns and target_col not in normalized.columns:
            normalized = normalized.rename(columns={source_col: target_col})

    return normalized


def generate_strategic_report(data_dir: str | Path, exports_dir: str | Path) -> dict[str, str]:
    """Generate complete KPI dashboard JSON and strategic report artifacts.

    Input files are resolved under ``data_dir`` using canonical names:
    ``loan_data.csv``, ``real_payment.csv``, ``customer_data.csv``,
    and optional ``payment_schedule.csv``.
    """
    data_root = Path(data_dir)
    exports_root = Path(exports_dir)
    exports_root.mkdir(parents=True, exist_ok=True)

    loans_df = _normalize_columns(_read_optional_table(data_root / "loan_data.csv"))
    payments_df = _normalize_columns(_read_optional_table(data_root / "real_payment.csv"))
    customers_df = _normalize_columns(_read_optional_table(data_root / "customer_data.csv"))
    schedule_df = _normalize_columns(_read_optional_table(data_root / "payment_schedule.csv"))

    if loans_df.empty and payments_df.empty and customers_df.empty:
        raise ValueError(
            "CRITICAL: No input datasets found in data_dir. "
            "Expected at least one of loan_data.csv, real_payment.csv, customer_data.csv"
        )

    processor = KPICatalogProcessor(
        loans_df=loans_df,
        payments_df=payments_df,
        customers_df=customers_df,
        schedule_df=schedule_df,
    )
    extended_kpis = processor.get_all_kpis()

    dashboard_payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source_data_dir": str(data_root),
        "extended_kpis": extended_kpis,
    }
    dashboard_path = exports_root / "complete_kpi_dashboard.json"
    with dashboard_path.open("w", encoding="utf-8") as dashboard_file:
        json.dump(dashboard_payload, dashboard_file, indent=2, default=str)

    summary = build_strategic_summary(dashboard_payload)
    links = {
        "streamlit_local": "http://localhost:8501",
        "grafana_local": "http://localhost:3001/dashboards",
        "streamlit_prod": "https://abaco-analytics-dashboard.azurewebsites.net",
        "dashboard_docs": "docs/analytics/dashboards.md",
    }
    latest_json_path, latest_md_path = write_strategic_report(summary, links, exports_root)

    return {
        "dashboard_json": str(dashboard_path),
        "strategic_report_json": str(latest_json_path),
        "strategic_report_md": str(latest_md_path),
    }
