#!/bin/bash

# Demo Script - Shows all platform features
# This script demonstrates the key features mentioned in the problem statement

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "========================================================"
echo "🚀 Abaco Loans Analytics - Platform Demo"
echo "========================================================"
echo ""
echo "This demo shows answers to your questions:"
echo "1. Where is Grafana?"
echo "2. Where to see agent feedback?"
echo "3. Where to upload files?"
echo "4. Where are ML predictions?"
echo "5. How to setup authentication?"
echo ""
echo "========================================================"
echo ""

# Question 1: Grafana
echo -e "${BLUE}📊 Question 1: WHERE IS GRAFANA?${NC}"
echo ""
echo "Grafana monitoring is configured in docker-compose.monitoring.yml"
echo ""
echo "To start Grafana:"
echo -e "${GREEN}  bash scripts/start_grafana.sh${NC}"
echo ""
echo "Or manually:"
echo -e "${GREEN}  export GRAFANA_ADMIN_PASSWORD='your_password'${NC}"
echo -e "${GREEN}  docker-compose -f docker-compose.monitoring.yml up -d${NC}"
echo ""
echo "Access Grafana at: http://localhost:3001"
echo "Documentation: docs/PROMETHEUS_GRAFANA_QUICKSTART.md"
echo ""
read -p "Press Enter to continue..."
echo ""

# Question 2: Agent Feedback
echo -e "${BLUE}🤖 Question 2: WHERE TO SEE AGENT FEEDBACK?${NC}"
echo ""
echo "View agent feedback in multiple ways:"
echo ""
echo "1. Streamlit Dashboard (NEW!):"
echo -e "${GREEN}   streamlit run streamlit_app.py${NC}"
echo "   → Navigate to 'Agent Insights' page"
echo "   → View conversation history, analytics, export data"
echo ""
echo "2. Command Line Interface:"
echo -e "${GREEN}   python -m python.multi_agent.cli run-agent risk_analyst --query 'Your question'${NC}"
echo ""
echo "3. Raw Output Files:"
echo "   → Stored in: data/agent_outputs/"
echo "   → Format: <timestamp>_<agent_name>_response.json"
echo ""
echo "Available agents:"
echo "  - Risk Analyst"
echo "  - Growth Strategist"
echo "  - Operations Optimizer"
echo "  - Compliance Officer"
echo "  - Collections Specialist"
echo "  - Fraud Detection"
echo "  - Pricing Strategist"
echo "  - Retention Specialist"
echo "  - Database Designer"
echo ""
read -p "Press Enter to continue..."
echo ""

# Question 3: File Upload
echo -e "${BLUE}📤 Question 3: WHERE TO UPLOAD FILES FOR DAILY PROCESSING?${NC}"
echo ""
echo "Multiple upload options:"
echo ""
echo "1. Streamlit Dashboard (User-Friendly):"
echo -e "${GREEN}   streamlit run streamlit_app.py${NC}"
echo "   → Use sidebar 'Upload CSV Exports'"
echo "   → Drag & drop files"
echo "   → Automatic validation"
echo ""
echo "2. Command Line (Automated):"
echo -e "${GREEN}   python scripts/run_data_pipeline.py --input /path/to/loans.csv${NC}"
echo ""
echo "3. Scheduled Processing (Daily at 2 AM):"
echo "   → Setup cron job (see docs/USER_OPERATIONS_GUIDE.md)"
echo "   → Or use Azure Functions (host.json configured)"
echo ""
echo "4. API Endpoint (Coming Soon):"
echo -e "${GREEN}   curl -X POST http://localhost:8000/upload -F file=@loans.csv${NC}"
echo ""
read -p "Press Enter to continue..."
echo ""

# Question 4: ML & Predictions
echo -e "${BLUE}🔮 Question 4: WHERE ARE CONTINUOUS LEARNING & PREDICTIONS?${NC}"
echo ""
echo "Current Status:"
echo "  ✅ Multi-Agent AI System (9 agents using GPT-4/Claude/Gemini)"
echo "  ✅ 19 KPI calculation metrics"
echo "  ✅ Real-time anomaly detection"
echo "  ⏳ Traditional ML models (roadmap in progress)"
echo ""
echo "Use AI agents for predictions NOW:"
echo -e "${GREEN}  python -m python.multi_agent.cli --agent risk \\${NC}"
echo -e "${GREEN}    --query 'Predict default risk for \$50K loan, 12 months, customer score 0.15'${NC}"
echo ""
echo "ML Development Roadmap:"
echo "  Phase 1: Data Foundation (COMPLETE ✅)"
echo "  Phase 2: Model Development (3-6 months)"
echo "    - Default risk prediction"
echo "    - Customer churn forecasting"
echo "    - Dynamic pricing optimization"
echo "    - Fraud detection scoring"
echo "  Phase 3: Continuous Learning (6-9 months)"
echo "    - Automated retraining"
echo "    - Model monitoring"
echo "    - A/B testing framework"
echo ""
echo "Full roadmap: docs/ML_CONTINUOUS_LEARNING_ROADMAP.md"
echo ""
read -p "Press Enter to continue..."
echo ""

# Question 5: Authentication
echo -e "${BLUE}🔐 Question 5: HOW TO CREATE USERS & PASSWORDS?${NC}"
echo ""
echo "Three authentication options available:"
echo ""
echo "1. Streamlit Built-in Auth (15 min setup):"
echo "   → Simple password protection"
echo "   → Role-based access control"
echo "   → Best for: Internal teams"
echo ""
echo "2. FastAPI OAuth2 + JWT (Production-grade):"
echo "   → Token-based authentication"
echo "   → API security"
echo "   → Best for: External integrations"
echo ""
echo "3. Supabase Auth (Cloud-ready):"
echo "   → Managed authentication service"
echo "   → Built-in user management"
echo "   → Best for: Cloud deployments"
echo ""
echo "Setup instructions: docs/AUTHENTICATION_SETUP_GUIDE.md"
echo ""
echo "Quick start - Generate password hash:"
echo -e "${GREEN}  python -c \"import bcrypt; print(bcrypt.hashpw(b'password', bcrypt.gensalt()).decode())\"${NC}"
echo ""
read -p "Press Enter to continue..."
echo ""

# Summary
echo "========================================================"
echo -e "${GREEN}✅ DEMO COMPLETE${NC}"
echo "========================================================"
echo ""
echo "📚 Next Steps:"
echo ""
echo "1. Read the User Operations Guide:"
echo "   docs/USER_OPERATIONS_GUIDE.md"
echo ""
echo "2. Start components you need:"
echo "   - Grafana:    bash scripts/start_grafana.sh"
echo "   - Dashboard:  streamlit run streamlit_app.py"
echo "   - Pipeline:   python scripts/run_data_pipeline.py --input data.csv"
echo ""
echo "3. Setup authentication (optional):"
echo "   docs/AUTHENTICATION_SETUP_GUIDE.md"
echo ""
echo "4. Explore ML roadmap:"
echo "   docs/ML_CONTINUOUS_LEARNING_ROADMAP.md"
echo ""
echo "🆘 Need help? Check docs/USER_OPERATIONS_GUIDE.md"
echo ""
echo "========================================================"
