-- Reconcile monitoring KPI schema drift (A/B models), harden RLS,
-- and align pipeline KPI mapping coverage.
--
-- Canonical contract adopted:
--   monitoring.kpi_definitions:
--     kpi_key (PK), id (identity), name, display_name, category, unit,
--     direction, window, basis, owner_agent, source_tables, version,
--     formula/description/thresholds, timestamps.
--   monitoring.kpi_values:
--     kpi_key + (optional kpi_id), as_of_date, value_num (+ legacy value),
--     computed_at, status, snapshot_id (TEXT, NOT NULL), run_id, inputs_hash,
--     timestamps, unique(as_of_date, kpi_key, snapshot_id).
--
-- This migration is idempotent and safe across environments that currently
-- have either model variant.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS monitoring;

-- -----------------------------------------------------------------------------
-- 1) Bootstrap canonical tables when missing
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS monitoring.kpi_definitions (
  kpi_key TEXT PRIMARY KEY,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  display_name TEXT,
  description TEXT,
  formula TEXT,
  category TEXT NOT NULL DEFAULT 'Pipeline',
  unit TEXT NOT NULL DEFAULT 'unknown',
  direction TEXT NOT NULL DEFAULT 'higher_is_better',
  "window" TEXT NOT NULL DEFAULT 'current',
  basis TEXT NOT NULL DEFAULT 'portfolio',
  green NUMERIC,
  yellow NUMERIC,
  red NUMERIC,
  threshold_warning NUMERIC,
  threshold_critical NUMERIC,
  owner_agent TEXT NOT NULL DEFAULT 'monitoring',
  source_tables TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  version TEXT NOT NULL DEFAULT 'v1',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS monitoring.kpi_values (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  kpi_id BIGINT,
  kpi_key TEXT NOT NULL,
  as_of_date DATE NOT NULL,
  value NUMERIC,
  value_num NUMERIC,
  value_json JSONB,
  "timestamp" TIMESTAMPTZ,
  computed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status TEXT NOT NULL DEFAULT 'green',
  snapshot_id TEXT NOT NULL DEFAULT 'manual',
  run_id TEXT NOT NULL DEFAULT 'manual',
  inputs_hash TEXT NOT NULL DEFAULT 'manual',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (as_of_date, kpi_key, snapshot_id)
);

-- -----------------------------------------------------------------------------
-- 2) Reconcile kpi_definitions columns/defaults
-- -----------------------------------------------------------------------------

ALTER TABLE IF EXISTS monitoring.kpi_definitions
  ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS display_name TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS formula TEXT,
  ADD COLUMN IF NOT EXISTS category TEXT,
  ADD COLUMN IF NOT EXISTS unit TEXT,
  ADD COLUMN IF NOT EXISTS direction TEXT,
  ADD COLUMN IF NOT EXISTS "window" TEXT,
  ADD COLUMN IF NOT EXISTS basis TEXT,
  ADD COLUMN IF NOT EXISTS green NUMERIC,
  ADD COLUMN IF NOT EXISTS yellow NUMERIC,
  ADD COLUMN IF NOT EXISTS red NUMERIC,
  ADD COLUMN IF NOT EXISTS threshold_warning NUMERIC,
  ADD COLUMN IF NOT EXISTS threshold_critical NUMERIC,
  ADD COLUMN IF NOT EXISTS owner_agent TEXT,
  ADD COLUMN IF NOT EXISTS source_tables TEXT[],
  ADD COLUMN IF NOT EXISTS version TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

UPDATE monitoring.kpi_definitions
SET
  name = COALESCE(NULLIF(name, ''), kpi_key),
  display_name = COALESCE(
    NULLIF(display_name, ''),
    initcap(replace(COALESCE(NULLIF(name, ''), kpi_key), '_', ' '))
  ),
  category = COALESCE(NULLIF(category, ''), 'Pipeline'),
  unit = COALESCE(NULLIF(unit, ''), 'unknown'),
  direction = COALESCE(NULLIF(direction, ''), 'higher_is_better'),
  "window" = COALESCE(NULLIF("window", ''), 'current'),
  basis = COALESCE(NULLIF(basis, ''), 'portfolio'),
  owner_agent = COALESCE(NULLIF(owner_agent, ''), 'monitoring'),
  source_tables = COALESCE(source_tables, ARRAY[]::TEXT[]),
  version = COALESCE(NULLIF(version, ''), 'v1'),
  created_at = COALESCE(created_at, NOW()),
  updated_at = COALESCE(updated_at, NOW());

ALTER TABLE monitoring.kpi_definitions
  ALTER COLUMN name SET NOT NULL,
  ALTER COLUMN category SET DEFAULT 'Pipeline',
  ALTER COLUMN unit SET DEFAULT 'unknown',
  ALTER COLUMN direction SET DEFAULT 'higher_is_better',
  ALTER COLUMN "window" SET DEFAULT 'current',
  ALTER COLUMN basis SET DEFAULT 'portfolio',
  ALTER COLUMN owner_agent SET DEFAULT 'monitoring',
  ALTER COLUMN source_tables SET DEFAULT ARRAY[]::TEXT[],
  ALTER COLUMN version SET DEFAULT 'v1',
  ALTER COLUMN created_at SET DEFAULT NOW(),
  ALTER COLUMN updated_at SET DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS kpi_definitions_id_key
  ON monitoring.kpi_definitions(id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_indexes
    WHERE schemaname = 'monitoring'
      AND indexname = 'kpi_definitions_name_key'
  ) THEN
    IF EXISTS (
      SELECT name
      FROM monitoring.kpi_definitions
      GROUP BY name
      HAVING COUNT(*) > 1
    ) THEN
      RAISE NOTICE 'Skipping unique index kpi_definitions_name_key due to duplicate names.';
    ELSE
      EXECUTE 'CREATE UNIQUE INDEX kpi_definitions_name_key ON monitoring.kpi_definitions(name)';
    END IF;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION monitoring.sync_kpi_definitions_compat()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.kpi_key IS NULL AND NEW.name IS NOT NULL THEN
    NEW.kpi_key := NEW.name;
  ELSIF NEW.name IS NULL AND NEW.kpi_key IS NOT NULL THEN
    NEW.name := NEW.kpi_key;
  END IF;

  IF NEW.display_name IS NULL OR NEW.display_name = '' THEN
    NEW.display_name := initcap(replace(COALESCE(NEW.name, NEW.kpi_key), '_', ' '));
  END IF;

  IF NEW.updated_at IS NULL THEN
    NEW.updated_at := NOW();
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_kpi_definitions_compat ON monitoring.kpi_definitions;
CREATE TRIGGER trg_sync_kpi_definitions_compat
BEFORE INSERT OR UPDATE ON monitoring.kpi_definitions
FOR EACH ROW
EXECUTE FUNCTION monitoring.sync_kpi_definitions_compat();

-- -----------------------------------------------------------------------------
-- 3) Reconcile kpi_values columns/types/defaults/uniqueness
-- -----------------------------------------------------------------------------

ALTER TABLE IF EXISTS monitoring.kpi_values
  ADD COLUMN IF NOT EXISTS kpi_id BIGINT,
  ADD COLUMN IF NOT EXISTS kpi_key TEXT,
  ADD COLUMN IF NOT EXISTS as_of_date DATE,
  ADD COLUMN IF NOT EXISTS value NUMERIC,
  ADD COLUMN IF NOT EXISTS value_num NUMERIC,
  ADD COLUMN IF NOT EXISTS value_json JSONB,
  ADD COLUMN IF NOT EXISTS "timestamp" TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS computed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS snapshot_id TEXT,
  ADD COLUMN IF NOT EXISTS run_id TEXT,
  ADD COLUMN IF NOT EXISTS inputs_hash TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

DO $$
DECLARE
  v_data_type TEXT;
BEGIN
  SELECT data_type
    INTO v_data_type
  FROM information_schema.columns
  WHERE table_schema = 'monitoring'
    AND table_name = 'kpi_values'
    AND column_name = 'snapshot_id';

  IF v_data_type = 'uuid' THEN
    EXECUTE 'ALTER TABLE monitoring.kpi_values ALTER COLUMN snapshot_id TYPE TEXT USING snapshot_id::TEXT';
  END IF;
END;
$$;

UPDATE monitoring.kpi_values
SET
  value_num = COALESCE(value_num, value),
  value = COALESCE(value, value_num),
  "timestamp" = COALESCE("timestamp", computed_at, created_at, NOW()),
  computed_at = COALESCE(computed_at, "timestamp", created_at, NOW()),
  as_of_date = COALESCE(as_of_date, computed_at::DATE, CURRENT_DATE),
  status = COALESCE(NULLIF(status, ''), 'green'),
  snapshot_id = COALESCE(NULLIF(snapshot_id::TEXT, ''), 'manual'),
  run_id = COALESCE(NULLIF(run_id, ''), 'manual'),
  inputs_hash = COALESCE(NULLIF(inputs_hash, ''), 'manual'),
  created_at = COALESCE(created_at, NOW()),
  updated_at = COALESCE(updated_at, NOW())
WHERE TRUE;

-- Ensure definitions exist for every historical kpi_key before FK checks.
INSERT INTO monitoring.kpi_definitions (
  kpi_key,
  name,
  display_name,
  category,
  unit,
  direction,
  "window",
  basis,
  owner_agent,
  source_tables,
  version,
  description
)
SELECT
  kv.kpi_key,
  kv.kpi_key,
  initcap(replace(kv.kpi_key, '_', ' ')),
  'Pipeline',
  'unknown',
  'higher_is_better',
  'current',
  'portfolio',
  'monitoring',
  ARRAY['monitoring.kpi_values']::TEXT[],
  'v1',
  'Auto-registered during schema reconciliation'
FROM monitoring.kpi_values kv
LEFT JOIN monitoring.kpi_definitions kd
  ON kd.kpi_key = kv.kpi_key
WHERE kv.kpi_key IS NOT NULL
  AND kd.kpi_key IS NULL
GROUP BY kv.kpi_key;

WITH ranked AS (
  SELECT
    ctid,
    ROW_NUMBER() OVER (
      PARTITION BY as_of_date, kpi_key, COALESCE(snapshot_id, 'manual')
      ORDER BY computed_at DESC NULLS LAST, created_at DESC NULLS LAST, ctid DESC
    ) AS rn
  FROM monitoring.kpi_values
)
DELETE FROM monitoring.kpi_values kv
USING ranked r
WHERE kv.ctid = r.ctid
  AND r.rn > 1;

ALTER TABLE monitoring.kpi_values
  ALTER COLUMN kpi_key SET NOT NULL,
  ALTER COLUMN as_of_date SET NOT NULL,
  ALTER COLUMN snapshot_id SET DEFAULT 'manual',
  ALTER COLUMN snapshot_id SET NOT NULL,
  ALTER COLUMN status SET DEFAULT 'green',
  ALTER COLUMN status SET NOT NULL,
  ALTER COLUMN computed_at SET DEFAULT NOW(),
  ALTER COLUMN computed_at SET NOT NULL,
  ALTER COLUMN run_id SET DEFAULT 'manual',
  ALTER COLUMN run_id SET NOT NULL,
  ALTER COLUMN inputs_hash SET DEFAULT 'manual',
  ALTER COLUMN inputs_hash SET NOT NULL,
  ALTER COLUMN created_at SET DEFAULT NOW(),
  ALTER COLUMN updated_at SET DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_kpi_values_kpi_key
  ON monitoring.kpi_values(kpi_key);
CREATE INDEX IF NOT EXISTS idx_kpi_values_as_of_date
  ON monitoring.kpi_values(as_of_date);
CREATE INDEX IF NOT EXISTS idx_kpi_values_kpi_id
  ON monitoring.kpi_values(kpi_id);
CREATE UNIQUE INDEX IF NOT EXISTS kpi_values_as_of_date_kpi_key_snapshot_id_uidx
  ON monitoring.kpi_values(as_of_date, kpi_key, snapshot_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'kpi_values_kpi_key_fkey'
      AND connamespace = 'monitoring'::regnamespace
  ) THEN
    ALTER TABLE monitoring.kpi_values
      ADD CONSTRAINT kpi_values_kpi_key_fkey
      FOREIGN KEY (kpi_key)
      REFERENCES monitoring.kpi_definitions(kpi_key)
      ON DELETE RESTRICT
      NOT VALID;
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'kpi_values_kpi_id_fkey'
      AND connamespace = 'monitoring'::regnamespace
  ) THEN
    ALTER TABLE monitoring.kpi_values
      ADD CONSTRAINT kpi_values_kpi_id_fkey
      FOREIGN KEY (kpi_id)
      REFERENCES monitoring.kpi_definitions(id)
      ON DELETE SET NULL
      NOT VALID;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION monitoring.sync_kpi_values_compat()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.kpi_key IS NULL AND NEW.kpi_id IS NOT NULL THEN
    SELECT kd.kpi_key INTO NEW.kpi_key
    FROM monitoring.kpi_definitions kd
    WHERE kd.id = NEW.kpi_id;
  END IF;

  IF NEW.value_num IS NULL AND NEW.value IS NOT NULL THEN
    NEW.value_num := NEW.value;
  ELSIF NEW.value IS NULL AND NEW.value_num IS NOT NULL THEN
    NEW.value := NEW.value_num;
  END IF;

  IF NEW.computed_at IS NULL AND NEW."timestamp" IS NOT NULL THEN
    NEW.computed_at := NEW."timestamp";
  ELSIF NEW."timestamp" IS NULL AND NEW.computed_at IS NOT NULL THEN
    NEW."timestamp" := NEW.computed_at;
  END IF;

  IF NEW.as_of_date IS NULL THEN
    NEW.as_of_date := COALESCE(NEW.computed_at, NOW())::DATE;
  END IF;

  IF NEW.snapshot_id IS NULL OR NEW.snapshot_id = '' THEN
    NEW.snapshot_id := 'manual';
  END IF;

  IF NEW.status IS NULL OR NEW.status = '' THEN
    NEW.status := 'green';
  END IF;

  IF NEW.run_id IS NULL OR NEW.run_id = '' THEN
    NEW.run_id := 'manual';
  END IF;

  IF NEW.inputs_hash IS NULL OR NEW.inputs_hash = '' THEN
    NEW.inputs_hash := 'manual';
  END IF;

  IF NEW.updated_at IS NULL THEN
    NEW.updated_at := NOW();
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_kpi_values_compat ON monitoring.kpi_values;
CREATE TRIGGER trg_sync_kpi_values_compat
BEFORE INSERT OR UPDATE ON monitoring.kpi_values
FOR EACH ROW
EXECUTE FUNCTION monitoring.sync_kpi_values_compat();

-- -----------------------------------------------------------------------------
-- 4) Upsert function: guarantee one snapshot row per KPI definition
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION monitoring.upsert_daily_kpi_snapshot(
  p_target_date DATE DEFAULT CURRENT_DATE,
  p_snapshot_id TEXT DEFAULT 'auto-daily',
  p_run_id TEXT DEFAULT NULL
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = monitoring, public
AS $$
DECLARE
  v_rows INTEGER := 0;
  v_effective_run_id TEXT := COALESCE(p_run_id, 'daily_snapshot_' || to_char(p_target_date, 'YYYYMMDD'));
BEGIN
  WITH latest AS (
    SELECT DISTINCT ON (kv.kpi_key)
      kv.kpi_key,
      kv.kpi_id,
      COALESCE(kv.value_num, kv.value) AS effective_value,
      kv.status,
      COALESCE(kv.computed_at, kv."timestamp", kv.created_at, NOW()) AS source_timestamp
    FROM monitoring.kpi_values kv
    ORDER BY kv.kpi_key, kv.as_of_date DESC, kv.computed_at DESC NULLS LAST, kv.created_at DESC NULLS LAST
  ),
  upserted AS (
    INSERT INTO monitoring.kpi_values (
      kpi_id,
      kpi_key,
      value,
      value_num,
      "timestamp",
      computed_at,
      as_of_date,
      status,
      snapshot_id,
      run_id,
      inputs_hash
    )
    SELECT
      COALESCE(l.kpi_id, kd.id) AS kpi_id,
      kd.kpi_key,
      l.effective_value AS value,
      l.effective_value AS value_num,
      COALESCE(l.source_timestamp, NOW()) AS "timestamp",
      NOW() AS computed_at,
      p_target_date AS as_of_date,
      COALESCE(l.status, CASE WHEN l.effective_value IS NULL THEN 'unknown' ELSE 'green' END) AS status,
      p_snapshot_id AS snapshot_id,
      v_effective_run_id AS run_id,
      'auto-snapshot-v2' AS inputs_hash
    FROM monitoring.kpi_definitions kd
    LEFT JOIN latest l ON l.kpi_key = kd.kpi_key
    ON CONFLICT (as_of_date, kpi_key, snapshot_id)
    DO UPDATE SET
      kpi_id = EXCLUDED.kpi_id,
      value = EXCLUDED.value,
      value_num = EXCLUDED.value_num,
      "timestamp" = EXCLUDED."timestamp",
      computed_at = EXCLUDED.computed_at,
      status = EXCLUDED.status,
      run_id = EXCLUDED.run_id,
      inputs_hash = EXCLUDED.inputs_hash
    RETURNING 1
  )
  SELECT COUNT(*) INTO v_rows FROM upserted;

  RETURN COALESCE(v_rows, 0);
END;
$$;

COMMENT ON FUNCTION monitoring.upsert_daily_kpi_snapshot(DATE, TEXT, TEXT)
IS 'Upserts exactly one daily snapshot row per KPI definition using latest known KPI value (or NULL when absent).';

-- SECURITY DEFINER hardening: prevent PUBLIC/authenticated execution.
REVOKE ALL ON FUNCTION monitoring.upsert_daily_kpi_snapshot(DATE, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION monitoring.upsert_daily_kpi_snapshot(DATE, TEXT, TEXT) TO service_role;

-- -----------------------------------------------------------------------------
-- 5) Seed complete KPI definition coverage (pipeline + canonical aliases)
-- -----------------------------------------------------------------------------

INSERT INTO monitoring.kpi_definitions (
  kpi_key,
  name,
  display_name,
  category,
  unit,
  direction,
  "window",
  basis,
  owner_agent,
  source_tables,
  version,
  description
)
VALUES
  ('par_30', 'par_30', 'PAR 30', 'Asset Quality', 'percent', 'lower_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Portfolio at risk 30+ days'),
  ('par_90', 'par_90', 'PAR 90', 'Asset Quality', 'percent', 'lower_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Portfolio at risk 90+ days'),
  ('npl_rate', 'npl_rate', 'NPL Rate', 'Asset Quality', 'percent', 'lower_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Non-performing loan rate'),
  ('npl_90_ratio', 'npl_90_ratio', 'NPL 90 Ratio', 'Asset Quality', 'percent', 'lower_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Outstanding exposure with dpd>=90 or defaulted'),
  ('defaulted_outstanding_ratio', 'defaulted_outstanding_ratio', 'Defaulted Outstanding Ratio', 'Asset Quality', 'percent', 'lower_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Outstanding exposure currently defaulted'),
  ('default_rate', 'default_rate', 'Default Rate', 'Asset Quality', 'percent', 'lower_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Share of loans flagged defaulted'),
  ('loss_rate', 'loss_rate', 'Loss Rate', 'Asset Quality', 'percent', 'lower_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Outstanding defaulted balance over principal'),
  ('collection_rate_6m', 'collection_rate_6m', 'Collection Rate 6M', 'Cash Flow', 'percent', 'higher_is_better', '6m', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Collection rate over 6-month window'),
  ('collections_rate', 'collections_rate', 'Collections Rate', 'Cash Flow', 'percent', 'higher_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Collection efficiency payments vs scheduled'),
  ('recovery_rate', 'recovery_rate', 'Recovery Rate', 'Cash Flow', 'percent', 'higher_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Recoveries on defaulted portfolio'),
  ('cash_on_hand', 'cash_on_hand', 'Cash On Hand', 'Cash Flow', 'currency', 'higher_is_better', 'current', 'portfolio', 'monitoring', ARRAY['ledger'], 'v1', 'Current cash position'),
  ('portfolio_rotation', 'portfolio_rotation', 'Portfolio Rotation', 'Growth', 'percent', 'higher_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Portfolio rotation metric'),
  ('disbursement_volume', 'disbursement_volume', 'Disbursement Volume', 'Growth', 'currency', 'higher_is_better', 'mtd', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Disbursed principal volume'),
  ('disbursement_volume_mtd', 'disbursement_volume_mtd', 'Disbursement Volume MTD', 'Growth', 'currency', 'higher_is_better', 'mtd', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Disbursed principal month-to-date'),
  ('new_loans', 'new_loans', 'New Loans', 'Growth', 'count', 'higher_is_better', 'mtd', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'New loans originated'),
  ('new_loans_count_mtd', 'new_loans_count_mtd', 'New Loans Count MTD', 'Growth', 'count', 'higher_is_better', 'mtd', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Count of new loans month-to-date'),
  ('portfolio_growth_rate', 'portfolio_growth_rate', 'Portfolio Growth Rate', 'Growth', 'percent', 'higher_is_better', 'mom', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Month-over-month growth rate'),
  ('total_aum', 'total_aum', 'Total AUM', 'Portfolio Performance', 'currency', 'higher_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Total assets under management'),
  ('total_outstanding_balance', 'total_outstanding_balance', 'Total Outstanding Balance', 'Portfolio Performance', 'currency', 'higher_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Total outstanding balance active/defaulted'),
  ('loan_count', 'loan_count', 'Loan Count', 'Portfolio Performance', 'count', 'higher_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Total active/defaulted loans'),
  ('total_loans_count', 'total_loans_count', 'Total Loans Count', 'Portfolio Performance', 'count', 'higher_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Total active/defaulted loans (pipeline key)'),
  ('average_loan_size', 'average_loan_size', 'Average Loan Size', 'Portfolio Performance', 'currency', 'higher_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Average principal at unique-loan grain'),
  ('portfolio_yield', 'portfolio_yield', 'Portfolio Yield', 'Portfolio Performance', 'percent', 'higher_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Average annualized yield'),
  ('active_borrowers', 'active_borrowers', 'Active Borrowers', 'Customer Metrics', 'count', 'higher_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Distinct active/defaulted borrowers'),
  ('repeat_borrower_rate', 'repeat_borrower_rate', 'Repeat Borrower Rate', 'Customer Metrics', 'percent', 'higher_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Share of borrowers with multiple loans'),
  ('customer_lifetime_value', 'customer_lifetime_value', 'Customer Lifetime Value', 'Customer Metrics', 'currency', 'higher_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Average TPV per borrower'),
  ('processing_time', 'processing_time', 'Processing Time', 'Operational Metrics', 'days', 'lower_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Average processing time'),
  ('processing_time_avg', 'processing_time_avg', 'Processing Time Avg', 'Operational Metrics', 'months', 'lower_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Average term in months (pipeline key)'),
  ('automation_rate', 'automation_rate', 'Automation Rate', 'Operational Metrics', 'percent', 'higher_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Share of automated/bullet settlements'),
  ('top_10_borrower_concentration', 'top_10_borrower_concentration', 'Top 10 Borrower Concentration', 'Concentration', 'percent', 'lower_is_better', 'current', 'portfolio', 'monitoring', ARRAY['loan_tape'], 'v1', 'Outstanding concentration in top 10 borrowers')
ON CONFLICT (kpi_key) DO UPDATE
SET
  name = EXCLUDED.name,
  display_name = EXCLUDED.display_name,
  category = EXCLUDED.category,
  unit = EXCLUDED.unit,
  direction = EXCLUDED.direction,
  "window" = EXCLUDED."window",
  basis = EXCLUDED.basis,
  owner_agent = EXCLUDED.owner_agent,
  source_tables = EXCLUDED.source_tables,
  version = EXCLUDED.version,
  description = EXCLUDED.description,
  updated_at = NOW();

-- -----------------------------------------------------------------------------
-- 6) Harden RLS for sensitive tables without breaking KPI dashboard reads
-- -----------------------------------------------------------------------------

-- Remove permissive read-all policies generated by older migrations.
DO $$
DECLARE
  p RECORD;
BEGIN
  FOR p IN
    SELECT schemaname, tablename, policyname
    FROM pg_policies
    WHERE schemaname IN ('public', 'analytics')
      AND cmd = 'SELECT'
      AND lower(regexp_replace(COALESCE(qual, ''), '\s+', '', 'g')) IN ('true', '(true)')
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON %I.%I', p.policyname, p.schemaname, p.tablename);
  END LOOP;
END;
$$;

-- Restrict direct access to sensitive base tables to service_role.
DO $$
DECLARE
  t RECORD;
BEGIN
  FOR t IN
    SELECT * FROM (VALUES
      ('public', 'customer_data'),
      ('public', 'loan_data'),
      ('public', 'real_payment'),
      ('public', 'analytics_facts'),
      ('public', 'financial_statements'),
      ('public', 'payment_schedule'),
      ('public', 'historical_kpis'),
      ('public', 'data_lineage'),
      ('public', 'lineage_columns'),
      ('public', 'lineage_dependencies'),
      ('public', 'lineage_audit_log'),
      ('analytics', 'pipeline_runs'),
      ('analytics', 'raw_artifacts'),
      ('analytics', 'kpi_values'),
      ('analytics', 'data_quality_results')
    ) AS sensitive_tables(schema_name, table_name)
  LOOP
    IF EXISTS (
      SELECT 1
      FROM pg_tables
      WHERE schemaname = t.schema_name
        AND tablename = t.table_name
    ) THEN
      EXECUTE format('ALTER TABLE %I.%I ENABLE ROW LEVEL SECURITY', t.schema_name, t.table_name);
      EXECUTE format('REVOKE ALL ON TABLE %I.%I FROM anon, authenticated', t.schema_name, t.table_name);
      EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE %I.%I TO service_role', t.schema_name, t.table_name);

      IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = t.schema_name
          AND tablename = t.table_name
          AND policyname = 'service_role_full_access'
      ) THEN
        EXECUTE format(
          'CREATE POLICY service_role_full_access ON %I.%I FOR ALL TO service_role USING (auth.role() = ''service_role'') WITH CHECK (auth.role() = ''service_role'')',
          t.schema_name,
          t.table_name
        );
      END IF;
    END IF;
  END LOOP;
END;
$$;

-- Restrict direct base-table access in monitoring schema as well.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'monitoring' AND tablename = 'kpi_values') THEN
    ALTER TABLE monitoring.kpi_values ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS monitoring_read_all ON monitoring.kpi_values;
    DROP POLICY IF EXISTS authenticated_read_kpis ON monitoring.kpi_values;
    DROP POLICY IF EXISTS internal_authenticated_insert_kpis ON monitoring.kpi_values;
    REVOKE ALL ON TABLE monitoring.kpi_values FROM anon, authenticated;
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE monitoring.kpi_values TO service_role;
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'monitoring'
        AND tablename = 'kpi_values'
        AND policyname = 'service_role_full_access'
    ) THEN
      CREATE POLICY service_role_full_access
        ON monitoring.kpi_values
        FOR ALL
        TO service_role
        USING (auth.role() = 'service_role')
        WITH CHECK (auth.role() = 'service_role');
    END IF;
  END IF;

  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'monitoring' AND tablename = 'kpi_definitions') THEN
    ALTER TABLE monitoring.kpi_definitions ENABLE ROW LEVEL SECURITY;
    REVOKE ALL ON TABLE monitoring.kpi_definitions FROM anon, authenticated;
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE monitoring.kpi_definitions TO service_role;
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'monitoring'
        AND tablename = 'kpi_definitions'
        AND policyname = 'service_role_full_access'
    ) THEN
      CREATE POLICY service_role_full_access
        ON monitoring.kpi_definitions
        FOR ALL
        TO service_role
        USING (auth.role() = 'service_role')
        WITH CHECK (auth.role() = 'service_role');
    END IF;
  END IF;
END;
$$;

-- Keep dashboard/API compatibility via public views (read-only for anon/authenticated).
DROP VIEW IF EXISTS public.kpi_values CASCADE;
CREATE VIEW public.kpi_values AS
SELECT
  id,
  kpi_id,
  kpi_key,
  as_of_date,
  value,
  value_num,
  value_json,
  status,
  "timestamp",
  computed_at,
  snapshot_id,
  run_id,
  inputs_hash,
  created_at,
  updated_at
FROM monitoring.kpi_values;

DROP VIEW IF EXISTS public.kpi_definitions CASCADE;
CREATE VIEW public.kpi_definitions AS
SELECT
  kpi_key,
  id,
  name,
  display_name,
  description,
  formula,
  category,
  unit,
  direction,
  "window",
  basis,
  green,
  yellow,
  red,
  threshold_warning,
  threshold_critical,
  owner_agent,
  source_tables,
  version,
  created_at,
  updated_at
FROM monitoring.kpi_definitions;

GRANT SELECT ON public.kpi_values TO anon, authenticated, service_role;
GRANT INSERT, UPDATE, DELETE ON public.kpi_values TO service_role;
GRANT SELECT ON public.kpi_definitions TO anon, authenticated, service_role;

COMMIT;
