
on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        continue-on-error: true
        with:
          payload: '{"text":"A new push to main branch!"}'
        env:
